# Generated by Django 5.2.14 on 2026-05-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidades', '0002_tipo_conformidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='placa',
            field=models.CharField(max_length=100, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='tramiteconformidad',
            name='campo_modificado',
            field=models.CharField(max_length=50, verbose_name='Dato a cambiar'),
        ),
        migrations.AlterField(
            model_name='tramiteconformidad',
            name='certificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='conformidades.certificadoconformidad', verbose_name='Certificado Asociado'),
        ),
        migrations.AlterField(
            model_name='tramiteconformidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
