# Generated by Django 5.2.14 on 2026-05-13 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidades', '0004_certificadoconformidad_usuario'),
        ('glp', '0014_merge_20260512_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoconformidad',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión (Real)'),
        ),
        migrations.AddField(
            model_name='certificadoconformidad',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='glp.sedeconfiguracion', verbose_name='Sede'),
            preserve_default=False,
        ),
    ]
