# Generated by Django 5.2.14 on 2026-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidades', '0005_certificadoconformidad_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoconformidad',
            name='numero_certificado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° de Certificado'),
        ),
    ]
