# Generated by Django 5.1 on 2026-05-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidades', '0006_certificadoconformidad_numero_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoconformidad',
            name='propietario',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Titular / Propietario'),
        ),
    ]
