# Generated by Django 6.0.5 on 2026-06-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidades', '0007_certificadoconformidad_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadoconformidad',
            name='numero_vin',
        ),
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tramiteconformidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
