# Generated by Django 5.2.14 on 2026-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidades', '0008_remove_certificadoconformidad_numero_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tramiteconformidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
