# Generated by Django 5.2.14 on 2026-06-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidades', '0009_alter_certificadoconformidad_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Ancho (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Longitud (m)'),
        ),
    ]
