# Generated by Django 5.2.14 on 2026-06-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidades', '0010_alter_certificadoconformidad_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramiteconformidad',
            name='nota',
            field=models.TextField(blank=True, null=True, verbose_name='Nota de la Modificación'),
        ),
    ]
