# Generated by Django 6.0.3 on 2026-06-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidades', '0011_tramiteconformidad_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=150, verbose_name='Nombre de la Sede')),
                ('regla_fecha', models.CharField(choices=[('MISMO', 'Mismo día'), ('ANTES', '1 día antes'), ('ANTES_2', '2 días antes')], default='MISMO', max_length=10, verbose_name='Regla de Fecha')),
            ],
            options={
                'verbose_name': 'Sede Conformidad',
                'verbose_name_plural': 'Sedes Conformidad',
            },
        ),
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tramiteconformidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conformidades.sedeconformidad', verbose_name='Sede'),
        ),
    ]
