# Generated by Django 6.0.3 on 2026-06-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidades', '0012_sedeconformidad_alter_certificadoconformidad_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='altura',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='ancho',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ancho (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoconformidad',
            name='longitud',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Longitud (m)'),
        ),
    ]
