# Generated by Django 6.0.3 on 2026-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoGLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificado', models.CharField(max_length=20, unique=True, verbose_name='N° de Certificado')),
                ('tipo_certificado', models.CharField(blank=True, max_length=10, verbose_name='Tipo de Certificado')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('sede', models.CharField(max_length=100, verbose_name='Sede')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('propietario', models.CharField(max_length=200, verbose_name='Propietario')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoría')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Versión')),
                ('anio_fabricacion', models.CharField(max_length=4, verbose_name='Año de Fab.')),
                ('vin_serie', models.CharField(max_length=50, verbose_name='VIN / N° de serie')),
                ('numero_motor', models.CharField(max_length=50, verbose_name='N° Motor')),
                ('combustible', models.CharField(max_length=50, verbose_name='Combustible')),
                ('cilindrada', models.CharField(max_length=20, verbose_name='Cilindrada')),
                ('cilindros', models.CharField(max_length=10, verbose_name='Cilindros')),
                ('ejes', models.CharField(max_length=10, verbose_name='N° Ejes')),
                ('ruedas', models.CharField(max_length=10, verbose_name='N° Ruedas')),
                ('asientos', models.CharField(max_length=10, verbose_name='Asientos')),
                ('pasajeros', models.CharField(max_length=10, verbose_name='Pasajeros')),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Longitud (m)')),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ancho (m)')),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (m)')),
                ('peso_neto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso Neto (kg)')),
                ('peso_bruto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso Bruto (kg)')),
                ('carga_util', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Carga Útil (kg)')),
                ('reductor_marca', models.CharField(max_length=50, verbose_name='Marca Reductor')),
                ('reductor_modelo', models.CharField(max_length=50, verbose_name='Modelo Reductor')),
                ('reductor_serie', models.CharField(max_length=50, verbose_name='Serie Reductor')),
                ('cilindro_marca', models.CharField(max_length=50, verbose_name='Marca Cilindro')),
                ('cilindro_modelo', models.CharField(max_length=50, verbose_name='Modelo Cilindro')),
                ('cilindro_serie', models.CharField(max_length=50, verbose_name='Serie Cilindro')),
                ('cilindro_capacidad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Capacidad (L)')),
                ('cilindro_fecha_fab', models.CharField(max_length=20, verbose_name='Fecha Fabricación Cilindro')),
            ],
            options={
                'verbose_name': 'Certificado GLP',
                'verbose_name_plural': 'Certificados GLP',
            },
        ),
    ]
