# Generated by Django 6.0.3 on 2026-04-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=100, unique=True)),
                ('ciudad_anual', models.CharField(max_length=100)),
                ('fecha_anual', models.CharField(choices=[('MISMO', 'Mismo día'), ('ANTES', 'Un día antes')], max_length=10)),
                ('ciudad_inicial', models.CharField(max_length=100)),
                ('fecha_inicial', models.CharField(choices=[('MISMO', 'Mismo día'), ('ANTES', 'Un día antes')], max_length=10)),
            ],
        ),
    ]
