# Generated by Django 6.0.3 on 2026-04-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0002_sedeconfiguracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedeconfiguracion',
            name='ciudad_anual',
            field=models.CharField(choices=[('CHICLAYO', 'Chiclayo'), ('CHIMBOTE', 'Chimbote'), ('LIMA', 'Lima')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sedeconfiguracion',
            name='ciudad_inicial',
            field=models.CharField(choices=[('CHICLAYO', 'Chiclayo'), ('CHIMBOTE', 'Chimbote'), ('LIMA', 'Lima')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sedeconfiguracion',
            name='fecha_anual',
            field=models.CharField(choices=[('MISMO', 'Mismo día'), ('ANTES', 'Un día antes'), ('ANTES_2', '2 días antes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sedeconfiguracion',
            name='fecha_inicial',
            field=models.CharField(choices=[('MISMO', 'Mismo día'), ('ANTES', 'Un día antes'), ('ANTES_2', '2 días antes')], max_length=10),
        ),
    ]
