# Generated by Django 6.0.3 on 2026-05-04 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0003_alter_sedeconfiguracion_ciudad_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoglp',
            name='ciudad_glp_pdf',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='glp.sedeconfiguracion', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='sedeconfiguracion',
            name='nombre_sede',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Sede'),
        ),
    ]
