# Generated by Django 6.0.3 on 2026-05-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0004_certificadoglp_ciudad_glp_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoglp',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
