# Generated by Django 6.0.3 on 2026-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0005_certificadoglp_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoglp',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
