# Generated by Django 6.0.3 on 2026-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0006_alter_certificadoglp_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoglp',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Ancho (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='carga_util',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Carga Útil (kg)'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Longitud (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Peso Bruto (kg)'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='peso_neto',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Peso Neto (kg)'),
        ),
    ]
