# Generated by Django 5.2.14 on 2026-05-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0006_alter_certificadoglp_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoglp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sedeconfiguracion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
