# Generated by Django 6.0.3 on 2026-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0007_alter_certificadoglp_alto_alter_certificadoglp_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoglp',
            name='combustible',
            field=models.CharField(choices=[('ANUAL (GLP y otros)', [('BI.COMB.GLP', 'BI.COMB.GLP'), ('BI-COMBUSTIBLE GLP', 'BI-COMBUSTIBLE GLP'), ('BI COMB./GLP', 'BI COMB./GLP'), ('BI.COMBUS.GLP', 'BI.COMBUS.GLP'), ('BI.COMBUST.GLP', 'BI.COMBUST.GLP'), ('DUAL(GASOLINA/GLP)', 'DUAL(GASOLINA/GLP)'), ('GAS', 'GAS'), ('GAS NATURAL COMPR', 'GAS NATURAL COMPR'), ('GAS-GASOLINA', 'GAS-GASOLINA'), ('GASOL/DUAL', 'GASOL/DUAL'), ('GASOL/GLP', 'GASOL/GLP'), ('GAS-GLP', 'GAS-GLP'), ('GASOLINA-GAS', 'GASOLINA-GAS'), ('GASOLINA/GLP', 'GASOLINA/GLP'), ('GASOLINA/GNC', 'GASOLINA/GNC'), ('GLP', 'GLP'), ('GSL/GASP', 'GSL/GASP')]), ('INICIAL (GNV y otros)', [('BI COMB.-GNV', 'BI COMB.-GNV'), ('BI COMBUSTIBLE GNV', 'BI COMBUSTIBLE GNV'), ('BI-GNV', 'BI-GNV'), ('DUAL GNV', 'DUAL GNV'), ('GASOL/GNV', 'GASOL/GNV'), ('GASOLINA/GNV', 'GASOLINA/GNV'), ('GNV', 'GNV'), ('GASOLINA', 'GASOLINA'), ('GASOLINA PREMIUM SIN PLOMO', 'GASOLINA PREMIUM SIN PLOMO')])], max_length=50, verbose_name='Combustible'),
        ),
    ]
