# Generated by Django 6.0.3 on 2026-05-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0008_alter_certificadoglp_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoglp',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Ancho (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='cilindro_capacidad',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Capacidad (L)'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Longitud (m)'),
        ),
    ]
