# Generated by Django 6.0.3 on 2026-05-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0010_certificadoglp_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoglp',
            name='fecha_certificacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Documento'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión (Real)'),
        ),
    ]
