# Generated by Django 6.0.3 on 2026-05-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0011_certificadoglp_fecha_certificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoglp',
            name='alto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='ancho',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ancho (m)'),
        ),
        migrations.AlterField(
            model_name='certificadoglp',
            name='largo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Largo (m)'),
        ),
    ]
