# Generated by Django 6.0.3 on 2026-05-11 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0012_alter_certificadoglp_alto_alter_certificadoglp_ancho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoglp',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registro en Sistema'),
            preserve_default=False,
        ),
    ]
