# Generated by Django 5.2.14 on 2026-05-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0007_alter_certificadoglp_id_alter_sedeconfiguracion_id'),
        ('glp', '0013_certificadoglp_fecha_registro'),
    ]

    operations = [
    ]
