# Generated by Django 6.0.3 on 2026-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0013_certificadoglp_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoglp',
            name='cilindro_capacidad',
            field=models.CharField(max_length=20, verbose_name='Capacidad (L)'),
        ),
    ]
