# Generated by Django 5.1 on 2026-06-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0014_alter_certificadoglp_cilindro_capacidad'),
        ('glp', '0014_merge_20260512_0944'),
    ]

    operations = [
    ]
