# Generated by Django 5.2.14 on 2026-05-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0014_alter_certificadoglp_cilindro_capacidad'),
        ('glp', '0014_merge_20260512_0944'),
    ]

    operations = [
    ]
