# Generated by Django 6.0.3 on 2026-06-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0015_merge_20260610_0212'),
        ('glp', '0016_alter_certificadoglp_combustible_and_more'),
    ]

    operations = [
    ]
