# Generated by Django 5.2.14 on 2026-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0016_alter_certificadoglp_combustible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoglp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sedeconfiguracion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
