# Generated by Django 6.0.3 on 2026-06-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0017_alter_certificadoglp_id_alter_sedeconfiguracion_id'),
        ('glp', '0017_merge_20260612_1112'),
    ]

    operations = [
    ]
