# Generated by Django 6.0.3 on 2026-06-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glp', '0017_merge_20260611_1359'),
        ('glp', '0018_merge_20260614_1013'),
    ]

    operations = [
    ]
